# Generated by Django 3.0.5 on 2020-04-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='corp_type',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Financing', 'Financing'), ('Property Management', 'Property Management')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_incorporated',
            field=models.IntegerField(null=True),
        ),
    ]
