# Generated by Django 3.0.5 on 2020-04-28 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='assets',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='backyard_height',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='backyard_width',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='design',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='financing_secured',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='foundation_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='liabilities',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='permit_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='select_property',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='unit_bedrooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='visit_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='visit_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
